### ISSUE TITLE
怎么使用啊，怎么打开

### ISSUE THREAD

**Issue by Hallock** [Gltina/MarkSencent#1]

**Comment by leihui6** [comment]
~有release版本的，你可以用百度云下载((pan.baidu.com/s/12GZkpG_XpnNM6NOTP95ZJQ 提取码：n618 )) ,嗨呀，现在那个在线获取的功能没有了/(ㄒoㄒ)/~~，你可以打开本地的文件，用 云盘里的Tpo.zip，里面有TPO1-54的音频~ **（推荐直接使用v1.0版）**

**Comment by leihui6** [comment]
你好，现在可以直接下载安装包了，你可以尝试一下（谢谢~

**Comment by Hallock** [comment]
Thanks




------------------ 原始邮件 ------------------
发件人: "Lei Li"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 中午1:44
收件人: "Gltina/marksencent"<marksencent@noreply.github.com>;
抄送: "Hallock"<932084326@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Gltina/marksencent] 怎么使用啊，怎么打开 (#1)




你好，现在可以直接下载安装包了，你可以尝试一下（谢谢~

**Comment by Hallock** [comment]
请问all_lyrics该怎么使用能加载句子文本？现在只能听语音




------------------ 原始邮件 ------------------
发件人: "Lei Li"<notifications@github.com>; 
发送时间: 2019年7月17日(星期三) 晚上10:46
收件人: "Gltina/marksencent"<marksencent@noreply.github.com>; 
抄送: "Hallock"<932084326@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Gltina/marksencent] 怎么使用啊，怎么打开 (#1)




Closed #1.

**Comment by leihui6** [comment]
> 请问all_lyrics该怎么使用能加载句子文本？现在只能听语音
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Lei Li"<notifications@github.com>; 发送时间: 2019年7月17日(星期三) 晚上10:46 收件人: "Gltina/marksencent"<marksencent@noreply.github.com>; 抄送: "Hallock"<932084326@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [Gltina/marksencent] 怎么使用啊，怎么打开 (#1) Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

你可以直接使用v1.0的在线下载功能，直接下载听力部分的练习，下载完成后会自动开始你下载的听力。但是除了听力部分其他的，比如写作/口语部分的听力是没有文本的

**Comment by Hallock** [comment]
谢谢你的解答




------------------ 原始邮件 ------------------
发件人: "Lei Li"<notifications@github.com>;
发送时间: 2019年7月18日(星期四) 中午12:11
收件人: "Gltina/marksencent"<marksencent@noreply.github.com>;
抄送: "Hallock"<932084326@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Gltina/marksencent] 怎么使用啊，怎么打开 (#1)



 
请问all_lyrics该怎么使用能加载句子文本？现在只能听语音
 …
 ------------------ 原始邮件 ------------------ 发件人: "Lei Li"notifications@github.com; 发送时间: 2019年7月17日(星期三) 晚上10:46 收件人: "Gltina/marksencent"marksencent@noreply.github.com; 抄送: "Hallock"932084326@qq.com; "Author"author@noreply.github.com; 主题: Re: [Gltina/marksencent] 怎么使用啊，怎么打开 (#1) Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
你可以直接使用v1.0的在线下载功能，直接下载听力部分的练习，下载完成后会自动开始你下载的听力。但是除了听力部分其他的，比如写作/口语部分的听力是没有文本的

**Comment by yimingputongren** [comment]
有没有这个制作过程的视频，希望能在B站放一个讲解视频，我想学一下这个项目。

**Comment by leihui6** [comment]
> 有没有这个制作过程的视频，希望能在B站放一个讲解视频，我想学一下这个项目。

抱歉很久才回复，这个项目其实并不复杂，得益于Qt的快速开发我才能短时间内完成这个小项目。关于出视频来讲解，你是不是想学习Qt呀？如果是的话，我的这个其实都是很基础的功能可能满足不了你，我推荐你可以看b站上的基础向的视频/（plus 一本Qt相关手册）然后快速上手一个你想做的小工具来练手，这样学的会很快的。
