### ISSUE TITLE
有计划做支持mac,linux 的版本吗？

### ISSUE THREAD

**Issue by swinghu** [Gltina/MarkSencent#4]
有计划做支持mac,linux 的版本吗？Qt本来就是开源的支持多平台的

**Comment by leihui6** [comment]
no mac* device, 我其实也想弄来着

**Comment by swinghu** [comment]
此外，建议增加编译详细内容和步骤，周末想源码编译下，发现很多问题。
例如报错：
LINK : fatal error LNK1104: 无法打开文件“shell32.lib”

**Comment by leihui6** [comment]
你好

多谢你的建议，由于精力有限，确实有很多地方考虑不全，日后会将您的建议写在`readme`中

关于你的问题，请问你的编译环境以及Qt版本？
